"""MetaTrader 5 constants.

These mirror the values exported by the ``MetaTrader5`` package so the copier
logic (and its tests) can run without that Windows-only package installed.
"""

# Order / position types
ORDER_TYPE_BUY = 0
ORDER_TYPE_SELL = 1
ORDER_TYPE_BUY_LIMIT = 2
ORDER_TYPE_SELL_LIMIT = 3
ORDER_TYPE_BUY_STOP = 4
ORDER_TYPE_SELL_STOP = 5

MARKET_TYPES = frozenset({ORDER_TYPE_BUY, ORDER_TYPE_SELL})
PENDING_TYPES = frozenset(
    {ORDER_TYPE_BUY_LIMIT, ORDER_TYPE_SELL_LIMIT, ORDER_TYPE_BUY_STOP, ORDER_TYPE_SELL_STOP}
)
BUY_TYPES = frozenset({ORDER_TYPE_BUY, ORDER_TYPE_BUY_LIMIT, ORDER_TYPE_BUY_STOP})

# Mirror image of each order type, used by the "reverse" option.
# A buy limit (buy below market) mirrors to a sell stop (sell below market), etc.
REVERSE_TYPE = {
    ORDER_TYPE_BUY: ORDER_TYPE_SELL,
    ORDER_TYPE_SELL: ORDER_TYPE_BUY,
    ORDER_TYPE_BUY_LIMIT: ORDER_TYPE_SELL_STOP,
    ORDER_TYPE_SELL_STOP: ORDER_TYPE_BUY_LIMIT,
    ORDER_TYPE_SELL_LIMIT: ORDER_TYPE_BUY_STOP,
    ORDER_TYPE_BUY_STOP: ORDER_TYPE_SELL_LIMIT,
}

TYPE_NAMES = {
    ORDER_TYPE_BUY: "BUY",
    ORDER_TYPE_SELL: "SELL",
    ORDER_TYPE_BUY_LIMIT: "BUY_LIMIT",
    ORDER_TYPE_SELL_LIMIT: "SELL_LIMIT",
    ORDER_TYPE_BUY_STOP: "BUY_STOP",
    ORDER_TYPE_SELL_STOP: "SELL_STOP",
}

# Trade request actions
TRADE_ACTION_DEAL = 1
TRADE_ACTION_PENDING = 5
TRADE_ACTION_SLTP = 6
TRADE_ACTION_MODIFY = 7
TRADE_ACTION_REMOVE = 8

# Order filling policies (request field type_filling)
ORDER_FILLING_FOK = 0
ORDER_FILLING_IOC = 1
ORDER_FILLING_RETURN = 2

# Symbol filling_mode bit flags (what the broker allows)
SYMBOL_FILLING_FOK = 1
SYMBOL_FILLING_IOC = 2

ORDER_TIME_GTC = 0

# Symbol trade modes
SYMBOL_TRADE_MODE_DISABLED = 0
SYMBOL_TRADE_MODE_LONGONLY = 1
SYMBOL_TRADE_MODE_SHORTONLY = 2
SYMBOL_TRADE_MODE_CLOSEONLY = 3
SYMBOL_TRADE_MODE_FULL = 4

# Account margin modes
ACCOUNT_MARGIN_MODE_RETAIL_NETTING = 0
ACCOUNT_MARGIN_MODE_EXCHANGE = 1
ACCOUNT_MARGIN_MODE_RETAIL_HEDGING = 2

# Trade server return codes
TRADE_RETCODE_PLACED = 10008
TRADE_RETCODE_DONE = 10009
TRADE_RETCODE_DONE_PARTIAL = 10010
TRADE_RETCODE_INVALID_STOPS = 10016
TRADE_RETCODE_NO_CHANGES = 10025
TRADE_RETCODE_INVALID_FILL = 10030

SUCCESS_RETCODES = frozenset(
    {TRADE_RETCODE_PLACED, TRADE_RETCODE_DONE, TRADE_RETCODE_DONE_PARTIAL, TRADE_RETCODE_NO_CHANGES}
)
